### ISSUE TITLE
For top view installed rgbd, the plane extraction is not very good.

### ISSUE THREAD

**Issue by designershell** [ai4ce/peac#6]
When the depth camera is installed from top view, the depth map segmentation effect is not very good. What may be the reason?

**Comment by simbaforrest** [comment]
@designershell can you share some visuals, with more details such as the depth sensor you use?

**Comment by simbaforrest** [comment]
Closing this comment due to lack of response. If @designershell still faces the issue, please feel free to comment below and at me.
